### ISSUE TITLE
Erstellung der API Beschreibung

### ISSUE THREAD

**Issue by JDuef** [DeeDz-x/GameScore#2]
Identifizierung der Endpunkte
Erstellung der Beschreibung
Definition der Datenbank Views / Prozeduren etc.

**Comment by Philipp1643** [comment]
Die Beschreibung der API liegt im Verzeichniss datenmodell/api/ auf dem Branch datenmodell. Die Beschreibung lässt sich mit der Seite https://editor.swagger.io/ betrachten.

**Comment by JDaat** [comment]
Kurze Frage, wie soll z.B. ein Review erstellt werden ohne Payload bzw. Parameter ? :D @Philipp1643 @ZubatLvl101

**Comment by Philipp1643** [comment]
Stimmt, habe ich dort und wo es sonst noch fehlte gerade hinzugefügt.

**Comment by JDaat** [comment]
Ehm ist das aktuellste gepusht? Jetzt steht ja überall nur "platzhalter" drin? @Philipp1643 @ZubatLvl101

**Comment by Philipp1643** [comment]
Die placeholder sind jetzt durch JSON-Beschreibungen ersetzt worden.
